#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from parser.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "parser.y"

	int yylineno;
	char data_type[200];

#line 27 "parser.y"
typedef union{
	char str[1000];
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	NO_ELSE	258
#define	ELSE	259
#define	GE_OP	260
#define	LE_OP	261
#define	EQ_OP	262
#define	NE_OP	263
#define	IDENTIFIER	264
#define	CONSTANT	265
#define	STRING_LITERAL	266
#define	SIZEOF	267
#define	PTR_OP	268
#define	INC_OP	269
#define	DEC_OP	270
#define	LEFT_OP	271
#define	RIGHT_OP	272
#define	AND_OP	273
#define	OR_OP	274
#define	MUL_ASSIGN	275
#define	DIV_ASSIGN	276
#define	MOD_ASSIGN	277
#define	ADD_ASSIGN	278
#define	SUB_ASSIGN	279
#define	LEFT_ASSIGN	280
#define	RIGHT_ASSIGN	281
#define	AND_ASSIGN	282
#define	XOR_ASSIGN	283
#define	OR_ASSIGN	284
#define	DEFINE	285
#define	TYPEDEF	286
#define	EXTERN	287
#define	STATIC	288
#define	AUTO	289
#define	REGISTER	290
#define	CHAR	291
#define	SHORT	292
#define	INT	293
#define	LONG	294
#define	SIGNED	295
#define	UNSIGNED	296
#define	FLOAT	297
#define	DOUBLE	298
#define	CONST	299
#define	VOLATILE	300
#define	VOID	301
#define	STRUCT	302
#define	UNION	303
#define	ENUM	304
#define	CASE	305
#define	DEFAULT	306
#define	IF	307
#define	SWITCH	308
#define	WHILE	309
#define	DO	310
#define	FOR	311
#define	GOTO	312
#define	CONTINUE	313
#define	BREAK	314
#define	RETURN	315


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int NO_ELSE;
static const int ELSE;
static const int GE_OP;
static const int LE_OP;
static const int EQ_OP;
static const int NE_OP;
static const int IDENTIFIER;
static const int CONSTANT;
static const int STRING_LITERAL;
static const int SIZEOF;
static const int PTR_OP;
static const int INC_OP;
static const int DEC_OP;
static const int LEFT_OP;
static const int RIGHT_OP;
static const int AND_OP;
static const int OR_OP;
static const int MUL_ASSIGN;
static const int DIV_ASSIGN;
static const int MOD_ASSIGN;
static const int ADD_ASSIGN;
static const int SUB_ASSIGN;
static const int LEFT_ASSIGN;
static const int RIGHT_ASSIGN;
static const int AND_ASSIGN;
static const int XOR_ASSIGN;
static const int OR_ASSIGN;
static const int DEFINE;
static const int TYPEDEF;
static const int EXTERN;
static const int STATIC;
static const int AUTO;
static const int REGISTER;
static const int CHAR;
static const int SHORT;
static const int INT;
static const int LONG;
static const int SIGNED;
static const int UNSIGNED;
static const int FLOAT;
static const int DOUBLE;
static const int CONST;
static const int VOLATILE;
static const int VOID;
static const int STRUCT;
static const int UNION;
static const int ENUM;
static const int CASE;
static const int DEFAULT;
static const int IF;
static const int SWITCH;
static const int WHILE;
static const int DO;
static const int FOR;
static const int GOTO;
static const int CONTINUE;
static const int BREAK;
static const int RETURN;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,NO_ELSE=258
	,ELSE=259
	,GE_OP=260
	,LE_OP=261
	,EQ_OP=262
	,NE_OP=263
	,IDENTIFIER=264
	,CONSTANT=265
	,STRING_LITERAL=266
	,SIZEOF=267
	,PTR_OP=268
	,INC_OP=269
	,DEC_OP=270
	,LEFT_OP=271
	,RIGHT_OP=272
	,AND_OP=273
	,OR_OP=274
	,MUL_ASSIGN=275
	,DIV_ASSIGN=276
	,MOD_ASSIGN=277
	,ADD_ASSIGN=278
	,SUB_ASSIGN=279
	,LEFT_ASSIGN=280
	,RIGHT_ASSIGN=281
	,AND_ASSIGN=282
	,XOR_ASSIGN=283
	,OR_ASSIGN=284
	,DEFINE=285
	,TYPEDEF=286
	,EXTERN=287
	,STATIC=288
	,AUTO=289
	,REGISTER=290
	,CHAR=291
	,SHORT=292
	,INT=293
	,LONG=294
	,SIGNED=295
	,UNSIGNED=296
	,FLOAT=297
	,DOUBLE=298
	,CONST=299
	,VOLATILE=300
	,VOID=301
	,STRUCT=302
	,UNION=303
	,ENUM=304
	,CASE=305
	,DEFAULT=306
	,IF=307
	,SWITCH=308
	,WHILE=309
	,DO=310
	,FOR=311
	,GOTO=312
	,CONTINUE=313
	,BREAK=314
	,RETURN=315


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::NO_ELSE=258;
const int YY_parse_CLASS::ELSE=259;
const int YY_parse_CLASS::GE_OP=260;
const int YY_parse_CLASS::LE_OP=261;
const int YY_parse_CLASS::EQ_OP=262;
const int YY_parse_CLASS::NE_OP=263;
const int YY_parse_CLASS::IDENTIFIER=264;
const int YY_parse_CLASS::CONSTANT=265;
const int YY_parse_CLASS::STRING_LITERAL=266;
const int YY_parse_CLASS::SIZEOF=267;
const int YY_parse_CLASS::PTR_OP=268;
const int YY_parse_CLASS::INC_OP=269;
const int YY_parse_CLASS::DEC_OP=270;
const int YY_parse_CLASS::LEFT_OP=271;
const int YY_parse_CLASS::RIGHT_OP=272;
const int YY_parse_CLASS::AND_OP=273;
const int YY_parse_CLASS::OR_OP=274;
const int YY_parse_CLASS::MUL_ASSIGN=275;
const int YY_parse_CLASS::DIV_ASSIGN=276;
const int YY_parse_CLASS::MOD_ASSIGN=277;
const int YY_parse_CLASS::ADD_ASSIGN=278;
const int YY_parse_CLASS::SUB_ASSIGN=279;
const int YY_parse_CLASS::LEFT_ASSIGN=280;
const int YY_parse_CLASS::RIGHT_ASSIGN=281;
const int YY_parse_CLASS::AND_ASSIGN=282;
const int YY_parse_CLASS::XOR_ASSIGN=283;
const int YY_parse_CLASS::OR_ASSIGN=284;
const int YY_parse_CLASS::DEFINE=285;
const int YY_parse_CLASS::TYPEDEF=286;
const int YY_parse_CLASS::EXTERN=287;
const int YY_parse_CLASS::STATIC=288;
const int YY_parse_CLASS::AUTO=289;
const int YY_parse_CLASS::REGISTER=290;
const int YY_parse_CLASS::CHAR=291;
const int YY_parse_CLASS::SHORT=292;
const int YY_parse_CLASS::INT=293;
const int YY_parse_CLASS::LONG=294;
const int YY_parse_CLASS::SIGNED=295;
const int YY_parse_CLASS::UNSIGNED=296;
const int YY_parse_CLASS::FLOAT=297;
const int YY_parse_CLASS::DOUBLE=298;
const int YY_parse_CLASS::CONST=299;
const int YY_parse_CLASS::VOLATILE=300;
const int YY_parse_CLASS::VOID=301;
const int YY_parse_CLASS::STRUCT=302;
const int YY_parse_CLASS::UNION=303;
const int YY_parse_CLASS::ENUM=304;
const int YY_parse_CLASS::CASE=305;
const int YY_parse_CLASS::DEFAULT=306;
const int YY_parse_CLASS::IF=307;
const int YY_parse_CLASS::SWITCH=308;
const int YY_parse_CLASS::WHILE=309;
const int YY_parse_CLASS::DO=310;
const int YY_parse_CLASS::FOR=311;
const int YY_parse_CLASS::GOTO=312;
const int YY_parse_CLASS::CONTINUE=313;
const int YY_parse_CLASS::BREAK=314;
const int YY_parse_CLASS::RETURN=315;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		282
#define	YYFLAG		-32768
#define	YYNTBASE	85

#define YYTRANSLATE(x) ((unsigned)(x) <= 315 ? yytranslate[x] : 139)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    78,     2,     2,     2,    16,    18,     2,    71,
    72,    14,    12,    76,    13,    75,    15,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    81,    82,     5,
     7,     6,    80,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    73,     2,    74,    79,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    83,    17,    84,    77,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     8,
     9,    10,    11,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63,    64,    65,
    66,    67,    68,    69,    70
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     8,    10,    12,    14,    18,    20,    22,
    27,    31,    36,    40,    44,    47,    50,    52,    56,    58,
    61,    64,    67,    70,    75,    77,    79,    81,    83,    85,
    87,    89,    94,    96,   100,   104,   108,   110,   114,   118,
   120,   124,   128,   130,   134,   138,   142,   146,   148,   152,
   156,   158,   162,   164,   168,   170,   174,   176,   180,   182,
   186,   188,   194,   196,   200,   202,   204,   206,   208,   210,
   212,   214,   216,   218,   220,   222,   224,   228,   230,   233,
   237,   239,   242,   244,   247,   249,   253,   255,   259,   261,
   263,   265,   267,   269,   271,   273,   275,   277,   279,   281,
   283,   285,   287,   289,   292,   294,   297,   299,   306,   312,
   316,   318,   320,   322,   325,   329,   331,   335,   338,   340,
   342,   346,   351,   355,   360,   365,   369,   371,   374,   376,
   380,   383,   385,   387,   391,   393,   396,   398,   402,   407,
   409,   413,   415,   417,   419,   421,   423,   426,   430,   434,
   439,   441,   444,   446,   449,   451,   454,   460,   468,   474,
   482,   489,   497,   500,   503,   506,   510,   512,   514,   519,
   523,   527
};

static const short yyrhs[] = {   137,
     0,    85,   137,     0,    87,    85,     0,    19,     0,    20,
     0,    21,     0,    71,   106,    72,     0,    40,     0,    86,
     0,    88,    73,   106,    74,     0,    88,    71,    72,     0,
    88,    71,    89,    72,     0,    88,    75,    19,     0,    88,
    23,    19,     0,    88,    24,     0,    88,    25,     0,   104,
     0,    89,    76,   104,     0,    88,     0,    24,    90,     0,
    25,    90,     0,    91,    92,     0,    22,    90,     0,    22,
    71,   126,    72,     0,    18,     0,    14,     0,    12,     0,
    13,     0,    77,     0,    78,     0,    90,     0,    71,   126,
    72,    92,     0,    92,     0,    93,    14,    92,     0,    93,
    15,    92,     0,    93,    16,    92,     0,    93,     0,    94,
    12,    93,     0,    94,    13,    93,     0,    94,     0,    95,
    26,    94,     0,    95,    27,    94,     0,    95,     0,    96,
     5,    95,     0,    96,     6,    95,     0,    96,     9,    95,
     0,    96,     8,    95,     0,    96,     0,    97,    10,    96,
     0,    97,    11,    96,     0,    97,     0,    98,    18,    97,
     0,    98,     0,    99,    79,    98,     0,    99,     0,   100,
    17,    99,     0,   100,     0,   101,    28,   100,     0,   101,
     0,   102,    29,   101,     0,   102,     0,   102,    80,   106,
    81,   103,     0,   103,     0,    90,   105,   104,     0,     7,
     0,    30,     0,    31,     0,    32,     0,    33,     0,    34,
     0,    35,     0,    36,     0,    37,     0,    38,     0,    39,
     0,   104,     0,   106,    76,   104,     0,   103,     0,   109,
    82,     0,   109,   110,    82,     0,   112,     0,   112,   109,
     0,   113,     0,   113,   109,     0,   111,     0,   110,    76,
   111,     0,   120,     0,   120,     7,   127,     0,    41,     0,
    42,     0,    43,     0,    44,     0,    45,     0,    56,     0,
    46,     0,    47,     0,    48,     0,    49,     0,    52,     0,
    53,     0,    50,     0,    51,     0,   115,     0,   113,   114,
     0,   113,     0,    54,   114,     0,    54,     0,   116,    19,
    83,   117,    84,    82,     0,   116,    83,   117,    84,    82,
     0,   116,    19,    82,     0,    57,     0,    58,     0,   118,
     0,   117,   118,     0,   114,   119,    82,     0,   120,     0,
   119,    76,   120,     0,   122,   121,     0,   121,     0,    19,
     0,    71,   120,    72,     0,   121,    73,   107,    74,     0,
   121,    73,    74,     0,   121,    71,   123,    72,     0,   121,
    71,   125,    72,     0,   121,    71,    72,     0,    14,     0,
    14,   122,     0,   124,     0,   123,    76,   124,     0,   109,
   120,     0,   109,     0,    19,     0,   125,    76,    19,     0,
   114,     0,   114,   120,     0,   104,     0,    83,   128,    84,
     0,    83,   128,    76,    84,     0,   127,     0,   128,    76,
   127,     0,   130,     0,   133,     0,   134,     0,   135,     0,
   136,     0,    83,    84,     0,    83,   132,    84,     0,    83,
   131,    84,     0,    83,   131,   132,    84,     0,   108,     0,
   131,   108,     0,   129,     0,   132,   129,     0,    82,     0,
   106,    82,     0,    62,    71,   106,    72,   129,     0,    62,
    71,   106,    72,   129,     4,   129,     0,    64,    71,   106,
    72,   129,     0,    65,   129,    64,    71,   106,    72,    82,
     0,    66,    71,   133,   133,    72,   129,     0,    66,    71,
   133,   133,   106,    72,   129,     0,    68,    82,     0,    69,
    82,     0,    70,    82,     0,    70,   106,    82,     0,   138,
     0,   108,     0,   109,   120,   131,   130,     0,   109,   120,
   130,     0,   120,   131,   130,     0,   120,   130,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    34,    35,    36,    40,    41,    42,    43,    47,    51,    52,
    53,    54,    55,    56,    57,    58,    62,    63,    67,    68,
    69,    70,    71,    72,    76,    77,    78,    79,    80,    81,
    85,    86,    90,    91,    92,    93,    97,    98,    99,   103,
   104,   105,   109,   110,   111,   112,   113,   117,   118,   119,
   123,   124,   128,   129,   133,   134,   138,   139,   143,   144,
   148,   149,   153,   154,   158,   159,   160,   161,   162,   163,
   164,   165,   166,   167,   168,   172,   173,   177,   181,   182,
   186,   187,   188,   189,   193,   194,   198,   199,   203,   204,
   205,   206,   207,   211,   212,   213,   214,   215,   216,   217,
   218,   219,   220,   224,   225,   226,   227,   231,   232,   233,
   237,   238,   242,   243,   247,   252,   253,   257,   258,   262,
   263,   264,   265,   266,   267,   268,   272,   273,   277,   278,
   282,   283,   287,   288,   292,   293,   297,   298,   299,   303,
   304,   308,   309,   310,   311,   312,   316,   317,   318,   319,
   323,   324,   328,   329,   333,   334,   338,   339,   343,   344,
   345,   346,   350,   351,   352,   353,   357,   358,   362,   363,
   364,   365
};

static const char * const yytname[] = {   "$","error","$illegal.","NO_ELSE",
"ELSE","'<'","'>'","'='","GE_OP","LE_OP","EQ_OP","NE_OP","'+'","'-'","'*'","'/'",
"'%'","'|'","'&'","IDENTIFIER","CONSTANT","STRING_LITERAL","SIZEOF","PTR_OP",
"INC_OP","DEC_OP","LEFT_OP","RIGHT_OP","AND_OP","OR_OP","MUL_ASSIGN","DIV_ASSIGN",
"MOD_ASSIGN","ADD_ASSIGN","SUB_ASSIGN","LEFT_ASSIGN","RIGHT_ASSIGN","AND_ASSIGN",
"XOR_ASSIGN","OR_ASSIGN","DEFINE","TYPEDEF","EXTERN","STATIC","AUTO","REGISTER",
"CHAR","SHORT","INT","LONG","SIGNED","UNSIGNED","FLOAT","DOUBLE","CONST","VOLATILE",
"VOID","STRUCT","UNION","ENUM","CASE","DEFAULT","IF","SWITCH","WHILE","DO","FOR",
"GOTO","CONTINUE","BREAK","RETURN","'('","')'","'['","']'","'.'","','","'~'",
"'!'","'^'","'?'","':'","';'","'{'","'}'","begin","primary_expression","Define",
"postfix_expression","argument_expression_list","unary_expression","unary_operator",
"cast_expression","multiplicative_expression","additive_expression","shift_expression",
"relational_expression","equality_expression","and_expression","exclusive_or_expression",
"inclusive_or_expression","logical_and_expression","logical_or_expression","conditional_expression",
"assignment_expression","assignment_operator","expression","constant_expression",
"declaration","declaration_specifiers","init_declarator_list","init_declarator",
"storage_class_specifier","type_specifier","specifier_qualifier_list","struct_or_union_specifier",
"struct_or_union","struct_declaration_list","struct_declaration","struct_declarator_list",
"declarator","direct_declarator","pointer","parameter_list","parameter_declaration",
"identifier_list","type_name","initializer","initializer_list","statement","compound_statement",
"declaration_list","statement_list","expression_statement","selection_statement",
"iteration_statement","jump_statement","external_declaration","function_definition",
""
};
#endif

static const short yyr1[] = {     0,
    85,    85,    85,    86,    86,    86,    86,    87,    88,    88,
    88,    88,    88,    88,    88,    88,    89,    89,    90,    90,
    90,    90,    90,    90,    91,    91,    91,    91,    91,    91,
    92,    92,    93,    93,    93,    93,    94,    94,    94,    95,
    95,    95,    96,    96,    96,    96,    96,    97,    97,    97,
    98,    98,    99,    99,   100,   100,   101,   101,   102,   102,
   103,   103,   104,   104,   105,   105,   105,   105,   105,   105,
   105,   105,   105,   105,   105,   106,   106,   107,   108,   108,
   109,   109,   109,   109,   110,   110,   111,   111,   112,   112,
   112,   112,   112,   113,   113,   113,   113,   113,   113,   113,
   113,   113,   113,   114,   114,   114,   114,   115,   115,   115,
   116,   116,   117,   117,   118,   119,   119,   120,   120,   121,
   121,   121,   121,   121,   121,   121,   122,   122,   123,   123,
   124,   124,   125,   125,   126,   126,   127,   127,   127,   128,
   128,   129,   129,   129,   129,   129,   130,   130,   130,   130,
   131,   131,   132,   132,   133,   133,   134,   134,   135,   135,
   135,   135,   136,   136,   136,   136,   137,   137,   138,   138,
   138,   138
};

static const short yyr2[] = {     0,
     1,     2,     2,     1,     1,     1,     3,     1,     1,     4,
     3,     4,     3,     3,     2,     2,     1,     3,     1,     2,
     2,     2,     2,     4,     1,     1,     1,     1,     1,     1,
     1,     4,     1,     3,     3,     3,     1,     3,     3,     1,
     3,     3,     1,     3,     3,     3,     3,     1,     3,     3,
     1,     3,     1,     3,     1,     3,     1,     3,     1,     3,
     1,     5,     1,     3,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     3,     1,     2,     3,
     1,     2,     1,     2,     1,     3,     1,     3,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     2,     1,     2,     1,     6,     5,     3,
     1,     1,     1,     2,     3,     1,     3,     2,     1,     1,
     3,     4,     3,     4,     4,     3,     1,     2,     1,     3,
     2,     1,     1,     3,     1,     2,     1,     3,     4,     1,
     3,     1,     1,     1,     1,     1,     2,     3,     3,     4,
     1,     2,     1,     2,     1,     2,     5,     7,     5,     7,
     6,     7,     2,     2,     2,     3,     1,     1,     4,     3,
     3,     2
};

static const short yydefact[] = {     0,
   127,   120,     8,    89,    90,    91,    92,    93,    95,    96,
    97,    98,   101,   102,    99,   100,    94,   111,   112,     0,
     0,     0,   168,     0,    81,    83,   103,     0,     0,   119,
     0,     1,   167,   128,     0,     2,     3,    79,     0,    85,
    87,    82,    84,     0,     0,     0,   151,     0,   172,     0,
     0,     0,   118,   121,     0,    80,     0,   170,     0,   110,
     0,   107,   105,     0,     0,   113,    27,    28,    26,    25,
     4,     5,     6,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,    29,    30,   155,   147,     9,    19,
    31,     0,    33,    37,    40,    43,    48,    51,    53,    55,
    57,    59,    61,    63,    76,     0,   153,   142,     0,     0,
   143,   144,   145,   146,    87,   152,   171,   133,   126,   132,
     0,   129,     0,   123,    31,    78,     0,    86,     0,   137,
    88,   169,     0,   106,   104,     0,   116,     0,   114,     0,
    23,     0,    20,    21,     0,     0,     0,     0,   163,   164,
   165,     0,     0,   135,     0,     0,    15,    16,     0,     0,
     0,    65,    66,    67,    68,    69,    70,    71,    72,    73,
    74,    75,     0,    22,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,   156,   149,     0,   148,   154,   131,
   124,     0,   125,     0,   122,   140,     0,     0,     0,   115,
   109,     0,     0,     0,     0,     0,   166,     7,   136,     0,
    14,    11,     0,    17,     0,    13,    64,    34,    35,    36,
    38,    39,    41,    42,    44,    45,    47,    46,    49,    50,
    52,    54,    56,    58,    60,     0,    77,   150,   130,   134,
     0,   138,   108,   117,    24,     0,     0,     0,     0,    32,
    12,     0,    10,     0,   139,   141,   157,   159,     0,     0,
     0,    18,    62,     0,     0,   161,     0,   158,   160,   162,
     0,     0
};

static const short yydefgoto[] = {    21,
    89,    22,    90,   223,    91,    92,    93,    94,    95,    96,
    97,    98,    99,   100,   101,   102,   103,   104,   105,   173,
   106,   127,    23,    48,    39,    40,    25,    26,    64,    27,
    28,    65,    66,   136,    29,    30,    31,   121,   122,   123,
   155,   131,   207,   107,   108,    50,   110,   111,   112,   113,
   114,    32,    33
};

static const short yypact[] = {   722,
    34,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,    18,
   430,   722,-32768,    -4,   858,   858,-32768,    -2,   815,    48,
   -10,-32768,-32768,-32768,   -21,-32768,   762,-32768,   -57,-32768,
   143,-32768,-32768,    22,   267,   220,-32768,    -4,-32768,   815,
   797,   545,    48,-32768,    18,-32768,   478,-32768,   815,-32768,
   267,   267,   267,    18,   738,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,   655,   669,   669,   -13,    -5,   444,    19,
    33,    40,   511,   593,-32768,-32768,-32768,-32768,-32768,    87,
   218,   683,-32768,   132,    67,   153,    89,   204,   136,    84,
   139,   141,   -18,-32768,-32768,   -38,-32768,-32768,   287,   354,
-32768,-32768,-32768,-32768,   160,-32768,-32768,-32768,-32768,    18,
    10,-32768,    16,-32768,-32768,-32768,   101,-32768,   478,-32768,
-32768,-32768,   828,-32768,-32768,   -37,-32768,    96,-32768,   593,
-32768,   683,-32768,-32768,   683,   683,   119,   526,-32768,-32768,
-32768,   -29,    31,    18,   134,   189,-32768,-32768,   559,   683,
   199,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   683,-32768,   683,   683,   683,   683,   683,   683,
   683,   683,   683,   683,   683,   683,   683,   683,   683,   683,
   683,   683,   683,   683,-32768,-32768,   377,-32768,-32768,-32768,
-32768,   858,-32768,   208,-32768,-32768,   -56,   155,    18,-32768,
-32768,   171,    41,    42,   175,   526,-32768,-32768,-32768,   683,
-32768,-32768,    77,-32768,    11,-32768,-32768,-32768,-32768,-32768,
   132,   132,    67,    67,   153,   153,   153,   153,    89,    89,
   204,   136,    84,   139,   141,   -27,-32768,-32768,-32768,-32768,
   152,-32768,-32768,-32768,-32768,   444,   444,   683,   641,-32768,
-32768,   683,-32768,   683,-32768,-32768,   243,-32768,    83,   444,
    85,-32768,-32768,   444,   176,-32768,   444,-32768,-32768,-32768,
   259,-32768
};

static const short yypgoto[] = {   238,
-32768,-32768,-32768,-32768,   -52,-32768,   -76,    38,    39,    20,
    35,    86,    90,    91,    92,    88,-32768,   -51,   -53,-32768,
   -77,-32768,     0,     5,-32768,   232,-32768,    12,   -49,-32768,
-32768,   214,   -63,-32768,   -12,   261,   292,-32768,    93,-32768,
   154,  -108,-32768,   -46,    43,    14,   187,  -145,-32768,-32768,
-32768,    -3,-32768
};


#define	YYLAST		916


static const short yytable[] = {   125,
   126,   139,   216,   130,    24,   152,   153,    35,     2,     1,
   192,    41,   134,   135,     2,   174,    44,    36,    55,   251,
   206,   141,   143,   144,    56,    24,    24,   252,    47,    42,
    43,     1,   147,    36,   154,   115,     2,   194,   209,   125,
    47,    24,   115,   195,   210,    47,   194,     1,   194,   116,
    54,   137,   217,   264,    59,   120,    63,   145,   116,   109,
    20,   193,   153,   199,   153,   146,    20,   213,   214,   139,
   259,    49,    63,    63,    63,   130,    63,    38,   178,   179,
    45,   201,   225,    58,   263,   202,   194,   203,    20,   148,
   154,   204,   117,   182,   183,    63,   184,   185,   228,   229,
   230,   132,   218,    60,    61,   224,   194,   200,   116,   156,
   157,   158,   256,   257,   149,   246,   194,   194,    51,   227,
    52,   150,   125,   125,   125,   125,   125,   125,   125,   125,
   125,   125,   125,   125,   125,   125,   125,   125,   125,   125,
   247,   219,   266,   260,    63,   175,   176,   177,   261,    57,
   199,    63,   262,   188,   275,   190,   277,   159,   194,   160,
   194,   161,   189,    67,    68,    69,    57,   125,   191,    70,
    71,    72,    73,    74,   205,    75,    76,   211,   180,   181,
   269,   271,   215,     4,     5,     6,     7,     8,     9,    10,
    11,    12,    13,    14,    15,    16,   254,   130,    17,    18,
    19,   235,   236,   237,   238,   220,   120,   221,   272,   267,
   268,   125,   273,   186,   187,   231,   232,   226,   233,   234,
   239,   240,    84,   276,   162,    46,   250,   278,    85,    86,
   280,    67,    68,    69,   129,   265,   253,    70,    71,    72,
    73,    74,   255,    75,    76,   258,   274,   163,   164,   165,
   166,   167,   168,   169,   170,   171,   172,   279,   282,    37,
     4,     5,     6,     7,     8,     9,    10,    11,    12,    13,
    14,    15,    16,   241,   133,    17,    18,    19,   242,   245,
   243,    77,   244,    78,    79,    80,   128,    81,    82,    83,
    84,    53,    34,   212,   249,   197,    85,    86,    67,    68,
    69,    87,    46,    88,    70,    71,    72,    73,    74,     0,
    75,    76,     9,    10,    11,    12,    13,    14,    15,    16,
    62,     0,    17,    18,    19,     0,     0,     4,     5,     6,
     7,     8,     9,    10,    11,    12,    13,    14,    15,    16,
     0,     0,    17,    18,    19,     0,     0,     0,    77,     0,
    78,    79,    80,     0,    81,    82,    83,    84,     0,     0,
     0,     0,     0,    85,    86,    67,    68,    69,    87,    46,
   196,    70,    71,    72,    73,    74,     0,    75,    76,     0,
     0,     0,     0,     0,     0,     0,     0,     0,    67,    68,
    69,     0,     0,     0,    70,    71,    72,    73,    74,     0,
    75,    76,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,    77,     0,    78,    79,    80,
     0,    81,    82,    83,    84,     0,     0,     0,     0,   281,
    85,    86,     0,     0,     0,    87,    46,   198,    77,     0,
    78,    79,    80,     1,    81,    82,    83,    84,     2,     0,
     0,     0,     0,    85,    86,    67,    68,    69,    87,    46,
   248,    70,    71,    72,    73,    74,     0,    75,    76,     0,
     4,     5,     6,     7,     8,     9,    10,    11,    12,    13,
    14,    15,    16,     0,     0,    17,    18,    19,     0,    67,
    68,    69,     0,     0,     0,    70,    71,    72,    73,    74,
    20,    75,    76,     0,     0,    77,     0,    78,    79,    80,
     0,    81,    82,    83,    84,     0,     0,     0,     0,     0,
    85,    86,    67,    68,    69,    87,    46,     0,    70,    71,
    72,    73,    74,     0,    75,    76,     0,    67,    68,    69,
     0,     0,     0,    70,    71,    72,    73,    74,    84,    75,
    76,     0,     0,     0,    85,    86,    67,    68,    69,     0,
   129,     0,    70,    71,    72,    73,    74,     0,    75,    76,
    67,    68,    69,     0,     0,     0,    70,    71,    72,    73,
    74,    84,    75,    76,     0,     0,     0,    85,    86,     0,
     0,     0,   151,     0,     0,     0,    84,     0,     0,     0,
     0,     0,    85,    86,    67,    68,    69,    87,     0,     0,
    70,    71,    72,    73,    74,    84,    75,    76,   124,     0,
     0,    85,    86,     0,     0,     0,     0,     0,     0,    84,
   222,     0,     0,     0,     0,    85,    86,     0,     9,    10,
    11,    12,    13,    14,    15,    16,    62,     0,    17,    18,
    19,     0,    67,    68,    69,     0,     0,     0,    70,    71,
    72,    73,    74,    84,    75,    76,    67,    68,    69,    85,
    86,     0,    70,    71,    72,    73,    74,     0,    75,    76,
    67,    68,    69,     0,     0,     0,    70,    71,    72,    73,
    74,     0,    75,    76,    67,    68,    69,     0,     0,     0,
    70,    71,    72,    73,    74,     0,    75,    76,     0,     0,
     0,    84,   270,     0,     0,     0,     0,    85,    86,     0,
     0,     0,     0,     0,     0,   140,     0,     0,     0,     0,
     0,    85,    86,     0,     0,     1,     0,     0,     0,   142,
     2,     0,     0,     0,     0,    85,    86,     0,     0,     0,
     0,     0,     0,    84,     0,     0,     0,     0,     0,    85,
    86,     3,     4,     5,     6,     7,     8,     9,    10,    11,
    12,    13,    14,    15,    16,     1,     0,    17,    18,    19,
     2,     0,     0,     9,    10,    11,    12,    13,    14,    15,
    16,    62,    20,    17,    18,    19,     0,     0,     0,     0,
     0,     0,     4,     5,     6,     7,     8,     9,    10,    11,
    12,    13,    14,    15,    16,   118,     0,    17,    18,    19,
     0,   138,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,    20,     0,     0,     0,     0,     4,     5,     6,
     7,     8,     9,    10,    11,    12,    13,    14,    15,    16,
     0,     0,    17,    18,    19,     4,     5,     6,     7,     8,
     9,    10,    11,    12,    13,    14,    15,    16,   119,     0,
    17,    18,    19,     9,    10,    11,    12,    13,    14,    15,
    16,    62,     0,    17,    18,    19,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,    46,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,   208,     0,    17,    18,    19
};

static const short yycheck[] = {    52,
    52,    65,   148,    57,     0,    83,    84,    20,    19,    14,
    29,    24,    62,    63,    19,    92,    19,    21,    76,    76,
   129,    74,    75,    76,    82,    21,    22,    84,    29,    25,
    26,    14,    79,    37,    84,    48,    19,    76,    76,    92,
    41,    37,    55,    82,    82,    46,    76,    14,    76,    50,
    72,    64,    82,    81,    41,    51,    45,    71,    59,    46,
    71,    80,   140,   110,   142,    71,    71,   145,   146,   133,
   216,    29,    61,    62,    63,   129,    65,    82,    12,    13,
    83,    72,   160,    41,    74,    76,    76,    72,    71,    71,
   140,    76,    50,     5,     6,    84,     8,     9,   175,   176,
   177,    59,    72,    82,    83,   159,    76,   120,   109,    23,
    24,    25,    72,    72,    82,   193,    76,    76,    71,   173,
    73,    82,   175,   176,   177,   178,   179,   180,   181,   182,
   183,   184,   185,   186,   187,   188,   189,   190,   191,   192,
   194,   154,   251,   220,   133,    14,    15,    16,    72,     7,
   197,   140,    76,    18,    72,    17,    72,    71,    76,    73,
    76,    75,    79,    12,    13,    14,     7,   220,    28,    18,
    19,    20,    21,    22,    74,    24,    25,    82,    26,    27,
   258,   259,    64,    41,    42,    43,    44,    45,    46,    47,
    48,    49,    50,    51,    52,    53,   209,   251,    56,    57,
    58,   182,   183,   184,   185,    72,   202,    19,   262,   256,
   257,   264,   264,    10,    11,   178,   179,    19,   180,   181,
   186,   187,    71,   270,     7,    83,    19,   274,    77,    78,
   277,    12,    13,    14,    83,    84,    82,    18,    19,    20,
    21,    22,    72,    24,    25,    71,     4,    30,    31,    32,
    33,    34,    35,    36,    37,    38,    39,    82,     0,    22,
    41,    42,    43,    44,    45,    46,    47,    48,    49,    50,
    51,    52,    53,   188,    61,    56,    57,    58,   189,   192,
   190,    62,   191,    64,    65,    66,    55,    68,    69,    70,
    71,    31,     1,   140,   202,   109,    77,    78,    12,    13,
    14,    82,    83,    84,    18,    19,    20,    21,    22,    -1,
    24,    25,    46,    47,    48,    49,    50,    51,    52,    53,
    54,    -1,    56,    57,    58,    -1,    -1,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    -1,    -1,    56,    57,    58,    -1,    -1,    -1,    62,    -1,
    64,    65,    66,    -1,    68,    69,    70,    71,    -1,    -1,
    -1,    -1,    -1,    77,    78,    12,    13,    14,    82,    83,
    84,    18,    19,    20,    21,    22,    -1,    24,    25,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    12,    13,
    14,    -1,    -1,    -1,    18,    19,    20,    21,    22,    -1,
    24,    25,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    62,    -1,    64,    65,    66,
    -1,    68,    69,    70,    71,    -1,    -1,    -1,    -1,     0,
    77,    78,    -1,    -1,    -1,    82,    83,    84,    62,    -1,
    64,    65,    66,    14,    68,    69,    70,    71,    19,    -1,
    -1,    -1,    -1,    77,    78,    12,    13,    14,    82,    83,
    84,    18,    19,    20,    21,    22,    -1,    24,    25,    -1,
    41,    42,    43,    44,    45,    46,    47,    48,    49,    50,
    51,    52,    53,    -1,    -1,    56,    57,    58,    -1,    12,
    13,    14,    -1,    -1,    -1,    18,    19,    20,    21,    22,
    71,    24,    25,    -1,    -1,    62,    -1,    64,    65,    66,
    -1,    68,    69,    70,    71,    -1,    -1,    -1,    -1,    -1,
    77,    78,    12,    13,    14,    82,    83,    -1,    18,    19,
    20,    21,    22,    -1,    24,    25,    -1,    12,    13,    14,
    -1,    -1,    -1,    18,    19,    20,    21,    22,    71,    24,
    25,    -1,    -1,    -1,    77,    78,    12,    13,    14,    -1,
    83,    -1,    18,    19,    20,    21,    22,    -1,    24,    25,
    12,    13,    14,    -1,    -1,    -1,    18,    19,    20,    21,
    22,    71,    24,    25,    -1,    -1,    -1,    77,    78,    -1,
    -1,    -1,    82,    -1,    -1,    -1,    71,    -1,    -1,    -1,
    -1,    -1,    77,    78,    12,    13,    14,    82,    -1,    -1,
    18,    19,    20,    21,    22,    71,    24,    25,    74,    -1,
    -1,    77,    78,    -1,    -1,    -1,    -1,    -1,    -1,    71,
    72,    -1,    -1,    -1,    -1,    77,    78,    -1,    46,    47,
    48,    49,    50,    51,    52,    53,    54,    -1,    56,    57,
    58,    -1,    12,    13,    14,    -1,    -1,    -1,    18,    19,
    20,    21,    22,    71,    24,    25,    12,    13,    14,    77,
    78,    -1,    18,    19,    20,    21,    22,    -1,    24,    25,
    12,    13,    14,    -1,    -1,    -1,    18,    19,    20,    21,
    22,    -1,    24,    25,    12,    13,    14,    -1,    -1,    -1,
    18,    19,    20,    21,    22,    -1,    24,    25,    -1,    -1,
    -1,    71,    72,    -1,    -1,    -1,    -1,    77,    78,    -1,
    -1,    -1,    -1,    -1,    -1,    71,    -1,    -1,    -1,    -1,
    -1,    77,    78,    -1,    -1,    14,    -1,    -1,    -1,    71,
    19,    -1,    -1,    -1,    -1,    77,    78,    -1,    -1,    -1,
    -1,    -1,    -1,    71,    -1,    -1,    -1,    -1,    -1,    77,
    78,    40,    41,    42,    43,    44,    45,    46,    47,    48,
    49,    50,    51,    52,    53,    14,    -1,    56,    57,    58,
    19,    -1,    -1,    46,    47,    48,    49,    50,    51,    52,
    53,    54,    71,    56,    57,    58,    -1,    -1,    -1,    -1,
    -1,    -1,    41,    42,    43,    44,    45,    46,    47,    48,
    49,    50,    51,    52,    53,    19,    -1,    56,    57,    58,
    -1,    84,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    71,    -1,    -1,    -1,    -1,    41,    42,    43,
    44,    45,    46,    47,    48,    49,    50,    51,    52,    53,
    -1,    -1,    56,    57,    58,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    72,    -1,
    56,    57,    58,    46,    47,    48,    49,    50,    51,    52,
    53,    54,    -1,    56,    57,    58,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    83,    41,    42,
    43,    44,    45,    46,    47,    48,    49,    50,    51,    52,
    53,    84,    -1,    56,    57,    58
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 4:
#line 40 "parser.y"
{ insertToHash(yyvsp[0].str, data_type , yylineno); ;
    break;}
case 83:
#line 188 "parser.y"
{ strcpy(data_type, yyvsp[0].str); ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 367 "parser.y"


#include "lex.yy.c"
#include <stdio.h>
#include <string.h>
int main(int argc, char *argv[])
{
	yyin = fopen(argv[1], "r");
	if(!yyparse())
		printf("\nParsing complete\n");
	else
		printf("\nParsing failed\n");

	fclose(yyin);
	display();
	disp();
	return 0;
}
//extern int lineno;
extern char *yytext;
yyerror(char *s) {
	printf("\nLine %d : %s\n", (yylineno), s);
}         
